extends Node

signal bossDefeated()
signal enemyAttack(enemyDamage)
signal playerAttack(playerDamage, area)
signal throwAxe(direction)
signal mobDeath(nodeName)
signal healthChanged(health)
signal healthPotionPicked(healPoints)
signal maxHealthPotionPicked(healPoints)
signal maxHealthChanged(health)
signal levelLoaded(scene)
signal playerDeath()
signal continuePressed()
signal quitPressed()
signal savePressed()
signal loadPressed()
